configVersion = 6

#Things that might get you into third person.
[scenarios]
	#Automatically go into third person when riding a boat?
	#Default: true
	boat = false
	#Automatically go into third person when riding a minecart?
	#Default: true
	cart = false
	#Automatically go into third person when riding an animal?
	#Default: true
	animal = false
	#Automatically go into third person when flying an elytra?
	#Default: true
	elytra = false
	#Automatically go into third person when doing the swimming animation?
	#Default: false
	swim = false
	#If 'true', the customPattern will be used, and riding anything matching it will toggle third person.
	#Default: false
	custom = false
	#If 'true', the ignorePattern will be used, and anything matching it will be ignored.
	#Default: false
	useIgnore = false

#Scenario configuration.
#Has no effect if the corresponding scenario is turned off.
[scenarioOptions]
	#Ticks of elytra flight required before the camera automatically toggles if the 'elytra' option is enabled.
	#Min: 0
	#Default: 7
	elytraDelay = 7
	#Ticks of swimming required before the camera automatically toggles if the 'swim' option is enabled.
	#Min: 0
	#Default: 0
	swimmingDelayStart = 0
	#Ticks of not swimming required before the camera restores if the 'swim' option is enabled.
	#Min: 0
	#Default: 10
	swimmingDelayEnd = 10
	#If 'true', your head has to completely exit the water to count as 'not swimming anymore', for the purposes of restoring
	#the camera when you're done swimming. If 'false', you just have to stop doing the swimming animation.
	#Default: true
	stickySwim = true
	#Entity IDs that match this regular expression will be considered if the 'custom' option is enabled.
	#Default: ^minecraft:(cow|chicken)$
	customPattern = "^minecraft:(cow|chicken)$"
	#Entity IDs that match this regular expression will be ignored if the 'useIgnore' option is enabled.
	#Default: ^examplemod:example$
	ignorePattern = "^examplemod:example$"

#Automatically exiting from third person.
[restoration]
	#When the situation that Auto Third Person put you into third person for is over,
	#the camera will be restored back to the way it was.
	#Default: true
	autoRestore = true
	#If 'true', pressing f5 after mounting something will prevent your camera
	#from being automatically restored to first-person when you dismount.
	#Default: true
	cancelAutoRestore = true

#Other stuff I threw in the mod.
[extras]
	#Skip the 'third-person front' camera mode when pressing F5.
	#Default: false
	skipFrontView = false
	#Dump a bunch of debug crap into the log.
	#Might be handy!
	#Default: false
	logSpam = false

